/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ReservationId = IDL.Nat;
export const Result_1 = IDL.Variant({ 'ok' : ReservationId, 'err' : IDL.Text });
export const MenuItemId = IDL.Nat;
export const MenuItem = IDL.Record({
  'id' : MenuItemId,
  'name' : IDL.Text,
  'isAvailable' : IDL.Bool,
  'description' : IDL.Text,
  'imageUrl' : IDL.Opt(IDL.Text),
  'isVegetarian' : IDL.Bool,
  'category' : IDL.Text,
  'price' : IDL.Nat,
});
export const Timestamp = IDL.Int;
export const Review = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'createdAt' : Timestamp,
  'reviewText' : IDL.Text,
  'rating' : IDL.Nat,
});
export const ReservationStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Reservation = IDL.Record({
  'id' : ReservationId,
  'status' : ReservationStatus,
  'date' : IDL.Text,
  'name' : IDL.Text,
  'specialRequests' : IDL.Opt(IDL.Text),
  'createdAt' : Timestamp,
  'time' : IDL.Text,
  'partySize' : IDL.Nat,
  'phoneNumber' : IDL.Text,
});
export const RestaurantInfo = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'openingHours' : IDL.Text,
  'phone' : IDL.Text,
});
export const Result = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });

export const idlService = IDL.Service({
  'createReservation' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Opt(IDL.Text)],
      [Result_1],
      [],
    ),
  'getAllMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'getAllReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'getMenuItemsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(MenuItem)],
      ['query'],
    ),
  'getReservationByPhone' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Reservation)],
      ['query'],
    ),
  'getRestaurantInfo' : IDL.Func([], [RestaurantInfo], ['query']),
  'getVegetarianItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'submitReview' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [Result], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ReservationId = IDL.Nat;
  const Result_1 = IDL.Variant({ 'ok' : ReservationId, 'err' : IDL.Text });
  const MenuItemId = IDL.Nat;
  const MenuItem = IDL.Record({
    'id' : MenuItemId,
    'name' : IDL.Text,
    'isAvailable' : IDL.Bool,
    'description' : IDL.Text,
    'imageUrl' : IDL.Opt(IDL.Text),
    'isVegetarian' : IDL.Bool,
    'category' : IDL.Text,
    'price' : IDL.Nat,
  });
  const Timestamp = IDL.Int;
  const Review = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'createdAt' : Timestamp,
    'reviewText' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const ReservationStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Reservation = IDL.Record({
    'id' : ReservationId,
    'status' : ReservationStatus,
    'date' : IDL.Text,
    'name' : IDL.Text,
    'specialRequests' : IDL.Opt(IDL.Text),
    'createdAt' : Timestamp,
    'time' : IDL.Text,
    'partySize' : IDL.Nat,
    'phoneNumber' : IDL.Text,
  });
  const RestaurantInfo = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'openingHours' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Result = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });
  
  return IDL.Service({
    'createReservation' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Opt(IDL.Text)],
        [Result_1],
        [],
      ),
    'getAllMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'getAllReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'getMenuItemsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(MenuItem)],
        ['query'],
      ),
    'getReservationByPhone' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Reservation)],
        ['query'],
      ),
    'getRestaurantInfo' : IDL.Func([], [RestaurantInfo], ['query']),
    'getVegetarianItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'submitReview' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [Result], []),
  });
};

export const init = ({ IDL }) => { return []; };