/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface MenuItem {
  'id' : MenuItemId,
  'name' : string,
  'isAvailable' : boolean,
  'description' : string,
  'imageUrl' : [] | [string],
  'isVegetarian' : boolean,
  'category' : string,
  'price' : bigint,
}
export type MenuItemId = bigint;
export interface Reservation {
  'id' : ReservationId,
  'status' : ReservationStatus,
  'date' : string,
  'name' : string,
  'specialRequests' : [] | [string],
  'createdAt' : Timestamp,
  'time' : string,
  'partySize' : bigint,
  'phoneNumber' : string,
}
export type ReservationId = bigint;
export type ReservationStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'confirmed' : null };
export interface RestaurantInfo {
  'name' : string,
  'email' : string,
  'address' : string,
  'openingHours' : string,
  'phone' : string,
}
export type Result = { 'ok' : bigint } |
  { 'err' : string };
export type Result_1 = { 'ok' : ReservationId } |
  { 'err' : string };
export interface Review {
  'id' : bigint,
  'customerName' : string,
  'createdAt' : Timestamp,
  'reviewText' : string,
  'rating' : bigint,
}
export type Timestamp = bigint;
export interface _SERVICE {
  'createReservation' : ActorMethod<
    [string, string, string, string, bigint, [] | [string]],
    Result_1
  >,
  'getAllMenuItems' : ActorMethod<[], Array<MenuItem>>,
  'getAllReviews' : ActorMethod<[], Array<Review>>,
  'getMenuItemsByCategory' : ActorMethod<[string], Array<MenuItem>>,
  'getReservationByPhone' : ActorMethod<[string], Array<Reservation>>,
  'getRestaurantInfo' : ActorMethod<[], RestaurantInfo>,
  'getVegetarianItems' : ActorMethod<[], Array<MenuItem>>,
  'submitReview' : ActorMethod<[string, bigint, string], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];